In [1]:
import numpy as np

In [3]:
one = np.arange(10, 30).reshape(4, 5)

In [4]:
two = np.arange(70, 50, -1).reshape(4, 5)

In [5]:
one

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
two

array([[70, 69, 68, 67, 66],
       [65, 64, 63, 62, 61],
       [60, 59, 58, 57, 56],
       [55, 54, 53, 52, 51]])

In [7]:
one + two

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [11]:
one // two

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
arr = np.arange(90).reshape(5, 3, 2, 3)

In [25]:
arr.shape

(5, 3, 2, 3)

In [27]:
arr +  np.arange(18).reshape(3, 2, 3)

array([[[[  0,   2,   4],
         [  6,   8,  10]],

        [[ 12,  14,  16],
         [ 18,  20,  22]],

        [[ 24,  26,  28],
         [ 30,  32,  34]]],


       [[[ 18,  20,  22],
         [ 24,  26,  28]],

        [[ 30,  32,  34],
         [ 36,  38,  40]],

        [[ 42,  44,  46],
         [ 48,  50,  52]]],


       [[[ 36,  38,  40],
         [ 42,  44,  46]],

        [[ 48,  50,  52],
         [ 54,  56,  58]],

        [[ 60,  62,  64],
         [ 66,  68,  70]]],


       [[[ 54,  56,  58],
         [ 60,  62,  64]],

        [[ 66,  68,  70],
         [ 72,  74,  76]],

        [[ 78,  80,  82],
         [ 84,  86,  88]]],


       [[[ 72,  74,  76],
         [ 78,  80,  82]],

        [[ 84,  86,  88],
         [ 90,  92,  94]],

        [[ 96,  98, 100],
         [102, 104, 106]]]])

In [31]:
arr +  np.arange(6).reshape(2, 3)

array([[[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 6,  8, 10],
         [ 9, 11, 13]],

        [[12, 14, 16],
         [15, 17, 19]]],


       [[[18, 20, 22],
         [21, 23, 25]],

        [[24, 26, 28],
         [27, 29, 31]],

        [[30, 32, 34],
         [33, 35, 37]]],


       [[[36, 38, 40],
         [39, 41, 43]],

        [[42, 44, 46],
         [45, 47, 49]],

        [[48, 50, 52],
         [51, 53, 55]]],


       [[[54, 56, 58],
         [57, 59, 61]],

        [[60, 62, 64],
         [63, 65, 67]],

        [[66, 68, 70],
         [69, 71, 73]]],


       [[[72, 74, 76],
         [75, 77, 79]],

        [[78, 80, 82],
         [81, 83, 85]],

        [[84, 86, 88],
         [87, 89, 91]]]])

In [30]:
arr

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]],


       [[[72, 73, 74],
         [75, 76, 77]],

        [[78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89]]]])

In [32]:
arr + 5

array([[[[ 5,  6,  7],
         [ 8,  9, 10]],

        [[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]],


       [[[23, 24, 25],
         [26, 27, 28]],

        [[29, 30, 31],
         [32, 33, 34]],

        [[35, 36, 37],
         [38, 39, 40]]],


       [[[41, 42, 43],
         [44, 45, 46]],

        [[47, 48, 49],
         [50, 51, 52]],

        [[53, 54, 55],
         [56, 57, 58]]],


       [[[59, 60, 61],
         [62, 63, 64]],

        [[65, 66, 67],
         [68, 69, 70]],

        [[71, 72, 73],
         [74, 75, 76]]],


       [[[77, 78, 79],
         [80, 81, 82]],

        [[83, 84, 85],
         [86, 87, 88]],

        [[89, 90, 91],
         [92, 93, 94]]]])

In [33]:
one

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
one.T

array([[10, 15, 20, 25],
       [11, 16, 21, 26],
       [12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29]])