In [2]:
import numpy as np

In [38]:
arr = np.arange(20).reshape(5, 4)

arr

arr.sum()

np.sum(range(30))

arr.sum(axis=0)

arr.sum(axis=1)

arr.mean()

arr.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [9]:
arr.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [10]:
arr.std()

5.766281297335398

In [11]:
arr.prod()

0

In [12]:
arr.prod(axis=0)

array([    0,  9945, 30240, 65835])

In [17]:
arr.sum(axis=0, keepdims=True)

array([[40, 45, 50, 55]])

In [21]:
np.sin(np.pi)

1.2246467991473532e-16

In [31]:
b = np.linspace(1, 10, 10)

In [28]:
a = np.linspace(0, np.pi, 10)

In [34]:
np.sin([0, 8])

array([0.        , 0.98935825])

In [30]:
np.exp(a)

array([ 1.        ,  1.41774255,  2.00999393,  2.84965391,  4.04007559,
        5.72778705,  8.1205274 , 11.51281719, 16.32221075, 23.14069263])

In [33]:
np.exp2(b)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])