In [1]:
import numpy as np

In [2]:
nums = range(2, 7)

In [20]:
arr = np.array(nums)

In [21]:
arr

array([2, 3, 4, 5, 6])

In [22]:
type(arr)

numpy.ndarray

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr.shape

(5,)

In [27]:
arr[0]

2

In [33]:
arr[-1]

6

In [44]:
arr[3: :-1]

array([5, 4, 3, 2])

In [40]:
two = np.arange(4, 20, 3, dtype=float)

In [41]:
two.size

6

In [42]:
## 2 - D with iters

In [55]:
li = [[2, 4, 6], [4, 6, 3, 9]]

In [56]:
arr = np.array(li)

In [57]:
arr

array([list([2, 4, 6]), list([4, 6, 3, 9])], dtype=object)

In [59]:
type(arr[0])

list

In [62]:
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
arr1 = np.arange(50)

In [82]:
arr2 = arr1.reshape(10, 5)

In [83]:
arr1[0] = 1000

In [84]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44],
       [  45,   46,   47,   48,   49]])

In [85]:
second = arr1.copy()

In [87]:
arr1[0] = 50

In [88]:
second

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49])