In [1]:
import numpy as np

In [8]:
np.ones(range(2, 4), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.full((3, 4), 33)

array([[33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33]])

In [14]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])