In [0]:
from keras.layers import Dense, Input
from keras.models import Model
from keras.datasets import mnist

import pandas as pd

from sklearn.preprocessing import OneHotEncoder

In [0]:
in_layer = Input((784,))
d1 = Dense(400, activation="sigmoid", name="chacha")(in_layer)
d2 = Dense(100, activation="sigmoid", name="mama")(d1)
d3 = Dense(10, activation="softmax", name="taya")(d2)

In [0]:
model = Model(in_layer, d3)

In [59]:
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 784)               0         
_________________________________________________________________
chacha (Dense)               (None, 400)               314000    
_________________________________________________________________
mama (Dense)                 (None, 100)               40100     
_________________________________________________________________
taya (Dense)                 (None, 10)                1010      
Total params: 355,110
Trainable params: 355,110
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [0]:
# ((X_train, y_train), (X_test, y_test)) = mnist.load_data()

In [0]:
mnist = pd.read_csv("sample_data/mnist_train_small.csv").values

In [0]:
X, y = mnist[:, 1:], mnist[:, 0]

In [0]:
ohe = OneHotEncoder(categories="auto")

In [0]:
y_hot = ohe.fit_transform(y.reshape(-1, 1))

In [0]:
y_oe = (y % 2)

In [64]:
model.fit(X, y_hot, epochs=5)

Epoch 1/5
19999/19999 [==============================] - 5s 267us/step - loss: 0.7071 - acc: 0.8336
Epoch 2/5
19999/19999 [==============================] - 5s 243us/step - loss: 0.3421 - acc: 0.9037
Epoch 3/5
19999/19999 [==============================] - 5s 241us/step - loss: 0.3059 - acc: 0.9096
Epoch 4/5
19999/19999 [==============================] - 5s 242us/step - loss: 0.2956 - acc: 0.9108
Epoch 5/5
19999/19999 [==============================] - 5s 240us/step - loss: 0.2834 - acc: 0.9132


In [32]:
y_oe.shape

(19999,)

In [66]:
(model.predict(X[:10])).argsort(axis=1)

array([[6, 4, 7, 2, 1, 9, 8, 0, 3, 5],
       [1, 6, 8, 2, 3, 4, 9, 5, 7, 0],
       [2, 6, 1, 8, 0, 3, 5, 4, 7, 9],
       [6, 4, 2, 7, 1, 8, 9, 0, 3, 5],
       [5, 6, 9, 1, 4, 0, 8, 7, 3, 2],
       [4, 1, 9, 7, 6, 8, 3, 2, 5, 0],
       [7, 3, 9, 4, 8, 1, 0, 5, 2, 6],
       [7, 2, 6, 4, 1, 9, 0, 8, 3, 5],
       [7, 1, 2, 4, 9, 3, 8, 0, 6, 5],
       [4, 6, 5, 0, 3, 7, 9, 1, 2, 8]])

In [54]:
y[:10]

array([5, 7, 9, 5, 2, 0, 6, 5, 5, 2])

In [0]:
import numpy as np

In [0]:
arr = np.array([100, 111])

In [75]:
(1 / (1 + np.exp(-arr)))

array([1., 1.])

In [76]:
np.exp(arr) / np.sum(np.exp(arr))

array([1.67014218e-05, 9.99983299e-01])