In [1]:
from keras.layers import Dense, Input
from keras.models import Model
from keras.datasets import mnist

import pandas as pd

from sklearn.preprocessing import OneHotEncoder

Using TensorFlow backend.


In [2]:
in_layer = Input((784,))
d1 = Dense(400, activation="sigmoid", name="chacha")(in_layer)
d2 = Dense(100, activation="sigmoid", name="mama")(d1)
d3 = Dense(10, activation="softmax", name="taya")(d2)

In [3]:
model = Model(in_layer, d3)

In [4]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
chacha (Dense)               (None, 400)               314000    
_________________________________________________________________
mama (Dense)                 (None, 100)               40100     
_________________________________________________________________
taya (Dense)                 (None, 10)                1010      
Total params: 355,110
Trainable params: 355,110
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
# ((X_train, y_train), (X_test, y_test)) = mnist.load_data()

In [6]:
mnist = pd.read_csv("../datasets/mnist_train_small.csv").values

In [7]:
X, y = mnist[:, 1:], mnist[:, 0]

In [8]:
ohe = OneHotEncoder(categories="auto")

In [9]:
y_hot = ohe.fit_transform(y.reshape(-1, 1))

In [10]:
y_oe = (y % 2)

In [11]:
model.fit(X, y_hot, epochs=5)

Epoch 1/5
19999/19999 [==============================] - 3s 143us/step - loss: 0.6229 - accuracy: 0.8433
Epoch 2/5
19999/19999 [==============================] - 2s 122us/step - loss: 0.3468 - accuracy: 0.9038
Epoch 3/5
19999/19999 [==============================] - 3s 130us/step - loss: 0.3081 - accuracy: 0.9086
Epoch 4/5
19999/19999 [==============================] - 3s 126us/step - loss: 0.2800 - accuracy: 0.9175
Epoch 5/5
19999/19999 [==============================] - 3s 139us/step - loss: 0.2800 - accuracy: 0.9163


In [12]:
y_oe.shape

(19999,)

In [13]:
(model.predict(X[:10])).argsort(axis=1)

array([[2, 7, 4, 6, 1, 9, 0, 8, 3, 5],
       [1, 6, 3, 8, 2, 4, 9, 5, 7, 0],
       [1, 2, 0, 8, 6, 3, 5, 7, 4, 9],
       [7, 2, 4, 1, 6, 9, 0, 8, 3, 5],
       [9, 6, 4, 1, 5, 7, 0, 3, 8, 2],
       [1, 4, 6, 7, 8, 9, 2, 3, 5, 0],
       [7, 9, 3, 0, 8, 4, 1, 2, 5, 6],
       [7, 4, 2, 1, 9, 0, 6, 3, 8, 5],
       [7, 0, 9, 2, 1, 4, 3, 8, 6, 5],
       [4, 0, 6, 9, 5, 1, 7, 3, 8, 2]])

In [14]:
y[:10]

array([5, 7, 9, 5, 2, 0, 6, 5, 5, 2])

In [15]:
import numpy as np

In [16]:
arr = np.array([100, 111])

In [17]:
(1 / (1 + np.exp(-arr)))

array([1., 1.])

In [18]:
np.exp(arr) / np.sum(np.exp(arr))

array([1.67014218e-05, 9.99983299e-01])